services:
  postgres:
    image: postgres:16
    container_name: sdp_postgres
    environment:
      POSTGRES_USER: sdp
      POSTGRES_PASSWORD: sdp
      POSTGRES_DB: sdpwarehouse
    ports:
      - "5432:5432"
    volumes:
    - sdp_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  sdp_pgdata:
